### ISSUE TITLE
cartridge-cli does not take run_dir from --cfg file

### ISSUE THREAD

**Issue by opomuc** [tarantool/cartridge-cli#46]
With this config:
```
app.router_server_1_0:
  listen: 3301
  instance_name: app.router_server_1_0
  log_format: json
  log_level: 5
  http_port: 8081
  memtx_memory: 1000000000
  advertise_uri: server_1:3301
  workdir: /home/vagrant/app/data/app.router_server_1_0
  run_dir: /home/vagrant/app/run
  data_dir: /home/vagrant/app/data
  log_dir: /home/vagrant/logs
  pid_file: /home/vagrant/app/run/app.router_server_1_0.pid
  log: /home/vagrant/logs/app.router_server_1_0.jsonl
```

Command:
```
./cartridge start app --cfg ./cartridge.cfg --verbose

Starting router_server_1_0...
.../share/tarantool/rocks/cartridge-cli/scm-1/bin/cartridge:2364: No such file or directory
```

But if add run_dir it goes forward:
```
./cartridge start app --cfg ./cartridge.cfg --run_dir /home/vagrant/app/run --verbose

Starting router_server_1_0...
execve failed: No such file or directory
.../share/tarantool/rocks/cartridge-cli/scm-1/bin/cartridge:2404: Child process exited unexpectedly
```
