### ISSUE TITLE
[4pt] Add an ability to configure stateful failover

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge-cli#507]

**Comment by dokshina** [comment]
Smth like this?

```
cartridge failover set-eventual

cartridge failover set-stateful-stateboard \
  --stateboard-uri <uri> \
  --stateboard-password <passwd> \

cartridge failover set-stateful-etcd2 ...

cartridge failover disable

```

And 

```
cartridge failover setup
```

that uses `failover.yml`:

```yaml
mode: stateful
state_provider: stateboard
stateboard_params: 
    uri: <uri>
    password: <password>
```
