### ISSUE TITLE
provide tarantool/setup-cartridge-cli github action

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/cartridge-cli#667]
There is a github action to install tarantool but no action to install cartridge-cli so one must manually install cartridge-cli after tarantool:

```yaml
- name: Install tarantool
  uses: tarantool/setup-tarantool@v1
  with:
    tarantool-version: '2.8.2'

- name: Set up the Tarantool packages repository
  run: curl -L https://tarantool.io/installer.sh | sudo -E bash -s -- --repo-only
- name: Install cartridge-cli
  run: apt install cartridge-cli

- name: pack docker image
  run: |
    cartridge pack docker --tag cartridge-app:${{ env.RELEASE_VERSION }}
```
